name: "DevSecOps Pipeline for typescript based react app."

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Run the unit test cases..
  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repo
        uses: actions/checkout@v4

      - name: Setup Nodejs Configuration
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependancies
        run: npm ci

      - name: Run Test Cases
        run: npm test || echo "No tests found, would add tests in a real project"

  # Check static code analysis..
  lint:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repo
        uses: actions/checkout@v4

      - name: Setup Nodejs Configuration
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependancies
        run: npm ci

      - name: Run Eslint
        run: npm run lint

  # Build the project and upload the artifactory..
  build:
    name: Build Code
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout Code Repo
        uses: actions/checkout@v4

      - name: Setup Nodejs Configuration
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependancies
        run: npm ci

      - name: Build the application
        run: npm run build

      - name: Project folder structure
        run: ls -ltr

      - name: Upload the build artifactory
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/

  docker:
    name: Build, Scan & Upload Docker Image
    runs-on: ubuntu-latest
    needs: [build]
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{github.repository_owner}}/react-app-dev-sec-ops-pipeline
      TOKEN: ${{secrets.TOKEN}}
    outputs:
      image_tag: ${{ steps.set_output.outputs.image_tag }}
    steps:
      - name: Checkout Code Repo
        uses: actions/checkout@v4

      - name: Download the artifact file
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.TOKEN}}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            latest

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
          load: true

      - name: Scan Docker image using Trivy for vulnabiliy check
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{github.repository_owner}}/react-app-dev-sec-ops-pipeline:sha-${{ github.sha }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Push Docker image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set image tag to output
        id: set_output
        run: echo "image_tag=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
